social:
  vk:
    oauth:
      clientId: 4623869
      clientSecret: WEPBnzOvUEJHZlWnF5z3
      redirectURI: http://localhost:8080/oauth2/authorize?provider=vk
      scope: email
      userInfoURL: https://api.vk.com/method/users.get?v=5.27&fields=sex,photo_200,email&access_token=%s